/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as ImportRouteImport } from './routes/import'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as CardsCardIdInvoiceRouteImport } from './routes/cards.$cardId.invoice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRoute,
} as any)
const CardsCardIdInvoiceRoute = CardsCardIdInvoiceRouteImport.update({
  id: '/$cardId/invoice',
  path: '/$cardId/invoice',
  getParentRoute: () => CardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRouteWithChildren
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/simulator': typeof SimulatorRoute
  '/transactions': typeof TransactionsRoute
  '/cards/': typeof CardsIndexRoute
  '/cards/$cardId/invoice': typeof CardsCardIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/simulator': typeof SimulatorRoute
  '/transactions': typeof TransactionsRoute
  '/cards': typeof CardsIndexRoute
  '/cards/$cardId/invoice': typeof CardsCardIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRouteWithChildren
  '/import': typeof ImportRoute
  '/investments': typeof InvestmentsRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/simulator': typeof SimulatorRoute
  '/transactions': typeof TransactionsRoute
  '/cards/': typeof CardsIndexRoute
  '/cards/$cardId/invoice': typeof CardsCardIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cards'
    | '/import'
    | '/investments'
    | '/settings'
    | '/share'
    | '/simulator'
    | '/transactions'
    | '/cards/'
    | '/cards/$cardId/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/import'
    | '/investments'
    | '/settings'
    | '/share'
    | '/simulator'
    | '/transactions'
    | '/cards'
    | '/cards/$cardId/invoice'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cards'
    | '/import'
    | '/investments'
    | '/settings'
    | '/share'
    | '/simulator'
    | '/transactions'
    | '/cards/'
    | '/cards/$cardId/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRouteWithChildren
  ImportRoute: typeof ImportRoute
  InvestmentsRoute: typeof InvestmentsRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SimulatorRoute: typeof SimulatorRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRoute
    }
    '/cards/$cardId/invoice': {
      id: '/cards/$cardId/invoice'
      path: '/$cardId/invoice'
      fullPath: '/cards/$cardId/invoice'
      preLoaderRoute: typeof CardsCardIdInvoiceRouteImport
      parentRoute: typeof CardsRoute
    }
  }
}

interface CardsRouteChildren {
  CardsIndexRoute: typeof CardsIndexRoute
  CardsCardIdInvoiceRoute: typeof CardsCardIdInvoiceRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsIndexRoute: CardsIndexRoute,
  CardsCardIdInvoiceRoute: CardsCardIdInvoiceRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRouteWithChildren,
  ImportRoute: ImportRoute,
  InvestmentsRoute: InvestmentsRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SimulatorRoute: SimulatorRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
